### ISSUE TITLE
Home Area under admin is blank

### ISSUE THREAD

**Issue by fusionsec** [snoopysecurity/dvws-node#7]
Hello, 
I'm able to logon dvws at http://dvws.local/home.html#admin), however in the Home area "All Accessible Areas can be found here"  is blank nothing listing vulnerabilities.  I'm able to access Note, Public Notes Search,and Passphase Gen.  Also, I'm not getting any errors in npm run dvws.

Thanks

**Comment by snoopysecurity** [comment]
Hi, the admin area (http://dvws.local/home.html#admin), isn't accessible by default. You will need to exploit the Mass Assignment issue (https://github.com/snoopysecurity/dvws-node/wiki/Mass-Assignment) in order to get an admin account. Then you will be able to access the admin area with that account. Does that answer you question?

**Comment by fusionsec** [comment]
Yes, thanks for your reply!  :)
